easy_admin:
    site_name: 'BlogProject'

    list:
        title: 'List of %%entity_label%%'

    entities:
        Category:
            class: App\Entity\Category
            label: Categories

        ContactUs:
            class: App\Entity\ContactUs
            label: Emails To Reply
        Posts:
            class: App\Entity\Posts
            label: "Posts"
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-12'}
                - title
                - {property: 'content', type: 'text_editor'}
                - createdAt
#                - updatedAt
                - published
#                - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-3'}
                - category
                - author
                - {property: 'thumbnailFile', type: 'vich_image', base_path: '%uploads_path%'}
            list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete']
              title: "Some posts"
              fields: ['title', 'content', 'createdAt', {property: 'thumbnail', type: 'image', template: 'vich_uploader_index.html.twig', base_path: '%uploads_path%'}]
              filters: ['published']
            show:
              fields:
                - title
                - {property: 'content', type: 'raw'}
                - createdAt
                - published
                - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}

        User:
            class: App\Entity\User


