vich_uploader:
    db_driver: orm

    mappings:
        post_thumbnails:
            uri_prefix: #%uploads_path%   #%uploads_path%
            upload_destination: '%kernel.project_dir%/public%uploads_path%'    #%uploads_path%

#            inject_on_load: false
#            delete_on_update: true
#            delete_on_remove: true