index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\AboutController::about

portfolio:
    path: /portfolio
    controller: App\Controller\PortfolioController::portfolio

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

contactAction:
    path: /contact/new-contact-us
    controller: App\Controller\ContactController::contactAction
    methods: GET|POST



dashboard:
    resource: 'routes/dashboard/dashboard.yaml'