index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\AboutController::about

portfolio:
    path: /portfolio
    controller: App\Controller\PortfolioController::portfolio.

contact:
    path: /contact
    controller: App\Controller\ContactController::contact